package table;

public enum Kind {
   CURRENT_MODULE_NAME,
   IMPORTED_MODULE,

   TYPE_NAME, UNDEFINED_TYPE_NAME,

   VAR, CONST,
   UNDEFINED_CONST,

   STANDARD_FUNCTION, STANDARD_PROCEDURE,

   GENERAL_EXPRESSION,
   CONST_EXPRESSION
}
